### ISSUE TITLE
Image size 

### ISSUE THREAD

**Issue by Wolrab1** [VinceG/vue-web-cam#9]
I'm using this version of the vue-webcam and I've got everything working which is great.

I've found that if you apply a width and height of 400 or anything square the image captured becomes squashed to fit the dimensions?

Is there away to set the ratio of the camera?

**Comment by VinceG** [comment]
@Wolrab1 hm looks like it is possible. See 

https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints#Applying_constraints

However, I am not sure if we should add the ability to pass in constraints as an object or just add the aspect ratio variable in like we have for width and height. I think constraints will be a better long term solution since it’ll allow to pass in any number of constraints but will require more work to make sure we can fetch the available constraints per webcam and allow to pass in an object of constraints.

Thoughts?

**Comment by jonathankeebler** [comment]
@VinceG @Wolrab1 I think I have a solution in this PR https://github.com/VinceG/vue-web-cam/pull/11
